import { chromium } from 'playwright';
const [, , x = '780', y = '650', name = 'hover'] = process.argv;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'no-preference' });
await page.goto('http://localhost:8080', { waitUntil: 'networkidle' });
await page.waitForTimeout(6000);
await page.mouse.move(+x, +y);
await page.waitForTimeout(900);
await page.screenshot({ path: `.shots/${name}.png`, clip: { x: 520, y: 420, width: 520, height: 440 } });
console.log('shot', name);
await browser.close();
